//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iHuya.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iHuya.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;uri&quot;:&quot;30001&quot;,&quot;version&quot;:&quot;2.2&quot;,&quot;context&quot;:&quot;WB-{SMALL}-{BIG}-&quot;,&quot;appId&quot;:&quot;5002&quot;,&quot;lcid&quot;:&quot;2052&quot;,&quot;byPass&quot;:&quot;3&quot;,&quot;sdid&quot;:&quot;73737534&quot;,&quot;requestId&quot;:&quot;73749187&quot;,&quot;data&quot;:{&quot;userName&quot;:&quot;{USERNAME}&quot;,&quot;password&quot;:&quot;{PASSWORD}&quot;,&quot;domainList&quot;:&quot;&quot;,&quot;remember&quot;:&quot;0&quot;,&quot;behavior&quot;:&quot;%5B%7B%22page.login%22%3A%220.005%22%7D%2C%7B%22button.UDBSdkPage.web%22%3A%221.686%2C656%2C612%22%7D%2C%7B%22input.l.passwd%22%3A%2214.227%22%7D%2C%7B%22input.l.account%22%3A%2216.107%22%7D%2C%7B%22button.UDBSdkLogin%22%3A%2218.541%2C697%2C550%22%7D%2C%7B%22input.l.ac [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string cookiesimple {
            get {
                return ResourceManager.GetString("cookiesimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string core {
            get {
                return ResourceManager.GetString("core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 data:image/png 的本地化字符串。
        /// </summary>
        public static string imageflag {
            get {
                return ResourceManager.GetString("imageflag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string JS {
            get {
                return ResourceManager.GetString("JS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;ua&quot;:&quot;wxapp&amp;iosliveroom_video&quot;,&quot;uid&quot;:{UID},&quot;sguid&quot;:&quot;{USERMD5}&quot;,&quot;m&quot;:[{&quot;name&quot;:&quot;fed.page.wxapp_video&quot;,&quot;its&quot;:{TIMERPICK},&quot;dim&quot;:{&quot;path&quot;:&quot;liveroom_video&quot;,&quot;useCache&quot;:&quot;1&quot;,&quot;networkType&quot;:&quot;wifi&quot;,&quot;platform&quot;:&quot;ios&quot;,&quot;moblieType&quot;:&quot;iPhone X (GSM+CDMA)&lt;iPhone10,3&gt;&quot;,&quot;wxVersion&quot;:&quot;7.0.2&quot;,&quot;wxsdkVersion&quot;:&quot;2.5.0&quot;,&quot;systemVersion&quot;:&quot;iOS 12.1&quot;},&quot;field&quot;:{&quot;requestTime&quot;:0,&quot;videoLoadTime&quot;:{VIDEOLOADTIMING}},&quot;exlog&quot;:{&quot;extdesc&quot;:&quot;&quot;}}]} 的本地化字符串。
        /// </summary>
        public static string metricHuya001 {
            get {
                return ResourceManager.GetString("metricHuya001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 { &quot;version&quot;: &quot;1.0&quot;,&quot;terminal&quot;: &quot;pc&quot;,&quot;deviceinfo&quot;: {&quot;ProcessorId&quot;:&quot;BFEBFBFF000906E{NONE1}&quot;,&quot;CPU_des&quot;:&quot;Intel64 Family 6 Model {NONE2} Stepping 13&quot;,&quot;CPU_name&quot;:&quot;Intel(R) Core(TM) i7-{NONE3}K CPU @ 3.60GHz&quot;,&quot;System_name&quot;:&quot;{NONE4}&quot;,&quot;Board_product&quot;:&quot;PRIME Z390-P&quot;,&quot;Video_product&quot;:&quot;&quot;,&quot;Network_product&quot;:&quot;WAN Miniport (IP)&quot;,&quot;MACAddress&quot;:&quot;EA:A2:20:52:41:{NONE5}&quot;,&quot;User_name&quot;:&quot;{NONE4}&quot;,&quot;OsVersion&quot;:&quot;6.2.9200&quot;,&quot;DiskInfo&quot;:&quot;C-total:102410.{NONE2}-free:36591.{NONE2};&quot;,&quot;cdid&quot;:&quot;{NONE6}&quot;,&quot;sdid&quot;:&quot;{sdid}&quot;}} 的本地化字符串。
        /// </summary>
        public static string printText {
            get {
                return ResourceManager.GetString("printText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;ua&quot;:&quot;web&amp;huya-main&quot;,&quot;uid&quot;:&quot;{UID}&quot;,&quot;sguid&quot;:&quot;{SGUID}&quot;,&quot;m&quot;:[{&quot;name&quot;:&quot;fed.page.pv&quot;,&quot;its&quot;:1543558252701,&quot;dim&quot;:{&quot;schema&quot;:&quot;https&quot;},&quot;field&quot;:{},&quot;exlog&quot;:{&quot;extdesc&quot;:&quot;Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36&quot;}}]} 的本地化字符串。
        /// </summary>
        public static string report1 {
            get {
                return ResourceManager.GetString("report1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;ua&quot;:&quot;web&amp;huya-main&quot;,&quot;uid&quot;:&quot;{UID}&quot;,&quot;sguid&quot;:&quot;{SGUID}&quot;,&quot;m&quot;:[{&quot;name&quot;:&quot;fed.page.loadStatus&quot;,&quot;its&quot;:1543558462894,&quot;dim&quot;:{&quot;schema&quot;:&quot;https&quot;,&quot;success&quot;:&quot;1&quot;},&quot;field&quot;:{},&quot;exlog&quot;:{&quot;extdesc&quot;:&quot;&quot;}},{&quot;name&quot;:&quot;fed.page.index&quot;,&quot;its&quot;:1543558462894,&quot;dim&quot;:{&quot;schema&quot;:&quot;https&quot;,&quot;path&quot;:&quot;huya-main-room&quot;,&quot;success&quot;:&quot;1&quot;},&quot;field&quot;:{&quot;value&quot;:16},&quot;exlog&quot;:{&quot;extdesc&quot;:&quot;network=0||sdkAnalysis=692.00||sdkDuration=4.00&quot;}},{&quot;name&quot;:&quot;fed.page.indexMess&quot;,&quot;its&quot;:1543558462959,&quot;dim&quot;:{&quot;schema&quot;:&quot;https&quot;,&quot;path&quot;:&quot;doLaunch&quot;,&quot;retcode&quot;:&quot;2&quot;},&quot;field&quot;:{},&quot;exlog&quot;:{&quot;ex [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string report2 {
            get {
                return ResourceManager.GetString("report2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;ua&quot;:&quot;web&amp;huya-main&quot;,&quot;uid&quot;:&quot;{UID}&quot;,&quot;sguid&quot;:&quot;{SGUID}&quot;,&quot;m&quot;:[{&quot;name&quot;:&quot;fed.page.index&quot;,&quot;its&quot;:1543558274840,&quot;dim&quot;:{&quot;schema&quot;:&quot;https&quot;,&quot;path&quot;:&quot;isPugcRoom&quot;,&quot;success&quot;:&quot;0&quot;},&quot;field&quot;:{&quot;value&quot;:5783},&quot;exlog&quot;:{&quot;extdesc&quot;:&quot;network=229||sdkAnalysis=901.70||sdkDuration=2.30&quot;}}]} 的本地化字符串。
        /// </summary>
        public static string report3 {
            get {
                return ResourceManager.GetString("report3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;ua&quot;:&quot;web&amp;huya-main&quot;,&quot;uid&quot;:&quot;{UID}&quot;,&quot;sguid&quot;:&quot;{SGUID}&quot;,&quot;m&quot;:[{&quot;name&quot;:&quot;fed.page.indexMess&quot;,&quot;its&quot;:1543558281833,&quot;dim&quot;:{&quot;schema&quot;:&quot;https&quot;,&quot;path&quot;:&quot;getActivityMsg&quot;,&quot;retcode&quot;:&quot;2&quot;},&quot;field&quot;:{},&quot;exlog&quot;:{&quot;extdesc&quot;:&quot;&quot;}}]} 的本地化字符串。
        /// </summary>
        public static string report4 {
            get {
                return ResourceManager.GetString("report4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;ua&quot;:&quot;web&amp;huya-main-room&quot;,&quot;uid&quot;:&quot;{UID}&quot;,&quot;sguid&quot;:&quot;{SGUID}&quot;,&quot;m&quot;:[{&quot;name&quot;:&quot;fed.page.index&quot;,&quot;its&quot;:1543558288663,&quot;dim&quot;:{&quot;schema&quot;:&quot;room-flv&quot;,&quot;path&quot;:&quot;AppCache&quot;,&quot;success&quot;:&quot;1&quot;},&quot;field&quot;:{&quot;value&quot;:0},&quot;exlog&quot;:{&quot;extdesc&quot;:&quot;&quot;}},{&quot;name&quot;:&quot;fed.page.index&quot;,&quot;its&quot;:1543558288663,&quot;dim&quot;:{&quot;schema&quot;:&quot;room-flv&quot;,&quot;path&quot;:&quot;DNS&quot;,&quot;success&quot;:&quot;1&quot;},&quot;field&quot;:{&quot;value&quot;:0},&quot;exlog&quot;:{&quot;extdesc&quot;:&quot;&quot;}},{&quot;name&quot;:&quot;fed.page.index&quot;,&quot;its&quot;:1543558288663,&quot;dim&quot;:{&quot;schema&quot;:&quot;room-flv&quot;,&quot;path&quot;:&quot;TCP&quot;,&quot;success&quot;:&quot;1&quot;},&quot;field&quot;:{&quot;value&quot;:0},&quot;exlog&quot;:{&quot;extdesc&quot;:&quot;&quot... 的本地化字符串。
        /// </summary>
        public static string report5 {
            get {
                return ResourceManager.GetString("report5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;ua&quot;:&quot;web&amp;huya-main-room&quot;,&quot;uid&quot;:&quot;{UID}&quot;,&quot;sguid&quot;:&quot;{SGUID}&quot;,&quot;m&quot;:[{&quot;name&quot;:&quot;fed.page.index&quot;,&quot;its&quot;:1543558297221,&quot;dim&quot;:{&quot;schema&quot;:&quot;room-normal&quot;,&quot;path&quot;:&quot;AppCache&quot;,&quot;success&quot;:&quot;1&quot;},&quot;field&quot;:{&quot;value&quot;:0},&quot;exlog&quot;:{&quot;extdesc&quot;:&quot;&quot;}},{&quot;name&quot;:&quot;fed.page.index&quot;,&quot;its&quot;:1543558297221,&quot;dim&quot;:{&quot;schema&quot;:&quot;room-normal&quot;,&quot;path&quot;:&quot;DNS&quot;,&quot;success&quot;:&quot;1&quot;},&quot;field&quot;:{&quot;value&quot;:0},&quot;exlog&quot;:{&quot;extdesc&quot;:&quot;&quot;}},{&quot;name&quot;:&quot;fed.page.index&quot;,&quot;its&quot;:1543558297221,&quot;dim&quot;:{&quot;schema&quot;:&quot;room-normal&quot;,&quot;path&quot;:&quot;TCP&quot;,&quot;success&quot;:&quot;1&quot;},&quot;field&quot;:{&quot;value&quot;:0},&quot;exlog&quot;:{&quot;extdesc&quot;:&q... 的本地化字符串。
        /// </summary>
        public static string report6 {
            get {
                return ResourceManager.GetString("report6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        public static string TestJs {
            get {
                return ResourceManager.GetString("TestJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GET {hysuffix} HTTP/1.1
        ///Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,video/x-mng,image/png,image/jpeg,image/gif;q=0.2,*/*;q=0.1
        ///Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
        ///Accept-Encoding: gzip,deflate
        ///Accept-Language: en-us,en;q=0.5
        ///Host: {hyprefix}
        ///Cookie: {Cookie}
        ///User-agent: HYSDK(Windows, 20000308) 的本地化字符串。
        /// </summary>
        public static string videodiymsg {
            get {
                return ResourceManager.GetString("videodiymsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GET /huyalive{hysuffix} HTTP/1.1
        ///Accept: text/xml,application/xml,application/xhtml+xml,text/html;q=0.9,text/plain;q=0.8,video/x-mng,image/png,image/jpeg,image/gif;q=0.2,*/*;q=0.1
        ///Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
        ///Accept-Encoding: gzip,deflate
        ///Accept-Language: en-us,en;q=0.5
        ///Host: {hyprefix}
        ///Cookie: {Cookie}
        ///User-agent: HYSDK(Windows, 20000308) 的本地化字符串。
        /// </summary>
        public static string VideoRequestMsg {
            get {
                return ResourceManager.GetString("VideoRequestMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GET {hysuffix}&amp;u={UFF}&amp;t=100&amp;sv={SVFLAG} HTTP/1.1
        ///Host: {hyprefix}
        ///User-Agent: VLC/2.2.4 LibVLC/2.2.4
        ///Range: bytes=0-
        ///Connection: close
        ///Icy-MetaData: 1
        ///Cookie: {Cookie} 的本地化字符串。
        /// </summary>
        public static string VideoRequestNew {
            get {
                return ResourceManager.GetString("VideoRequestNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GET {hysuffix} HTTP/1.1
        ///Host: {hyprefix}
        ///User-Agent: VLC/2.2.4 LibVLC/2.2.4
        ///Range: bytes=0-
        ///Connection: close
        ///Icy-MetaData: 1
        ///Cookie: {Cookie} 的本地化字符串。
        /// </summary>
        public static string VideoRequestNew2 {
            get {
                return ResourceManager.GetString("VideoRequestNew2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GET {hysuffix} HTTP/1.1
        ///Host: {hyprefix}
        ///Connection: keep-alive
        ///User-Agent: {USERAGENT}
        ///Cookie:  的本地化字符串。
        /// </summary>
        public static string VideoRequestWeb {
            get {
                return ResourceManager.GetString("VideoRequestWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;uri&quot;:&quot;40001&quot;,&quot;version&quot;:&quot;2.2&quot;,&quot;context&quot;:&quot;WB-{SMALL}-{BIG}-&quot;,&quot;appId&quot;:&quot;5002&quot;,&quot;lcid&quot;:&quot;2052&quot;,&quot;byPass&quot;:&quot;3&quot;,&quot;sdid&quot;:&quot;38968123&quot;,&quot;requestId&quot;:&quot;40556437&quot;,&quot;data&quot;:{&quot;strategy&quot;:&quot;4&quot;,&quot;uid&quot;:&quot;{UID}&quot;,&quot;authcode&quot;:&quot;{AUTHCODE}&quot;,&quot;sessionData&quot;:&quot;{SESSIONDATA}&quot;,&quot;remember&quot;:&quot;1&quot;}} 的本地化字符串。
        /// </summary>
        public static string webloginanti {
            get {
                return ResourceManager.GetString("webloginanti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;returnCode&quot;:10030 的本地化字符串。
        /// </summary>
        public static string webloginantiflag {
            get {
                return ResourceManager.GetString("webloginantiflag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;uri&quot;:&quot;30001&quot;,&quot;version&quot;:&quot;2.2&quot;,&quot;context&quot;:&quot;WB-{SMALL}-{BIG}-&quot;,&quot;appId&quot;:&quot;5002&quot;,&quot;lcid&quot;:&quot;2052&quot;,&quot;byPass&quot;:&quot;3&quot;,&quot;sdid&quot;:&quot;73737534&quot;,&quot;requestId&quot;:&quot;73749187&quot;,&quot;data&quot;:{&quot;userName&quot;:&quot;{USERNAME}&quot;,&quot;password&quot;:&quot;{PASSWORD}&quot;,&quot;authcode&quot;:&quot;{AUTHCODE}&quot;,&quot;sessionData&quot;:&quot;{SESSIONDATA}&quot;,&quot;domainList&quot;:&quot;&quot;,&quot;remember&quot;:&quot;1&quot;,&quot;behavior&quot;:&quot;%5B%7B%22page.login%22%3A%220.005%22%7D%2C%7B%22button.UDBSdkPage.web%22%3A%221.686%2C656%2C612%22%7D%2C%7B%22input.l.passwd%22%3A%2214.227%22%7D%2C%7B%22input.l.account%22%3A%2216.107%22%7D%2C%7B%22button.UDBSdkLog [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string webloginauth {
            get {
                return ResourceManager.GetString("webloginauth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;userNick&quot;:&quot; 的本地化字符串。
        /// </summary>
        public static string weblogincheckpre {
            get {
                return ResourceManager.GetString("weblogincheckpre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot; 的本地化字符串。
        /// </summary>
        public static string webloginchecksuff {
            get {
                return ResourceManager.GetString("webloginchecksuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;description&quot;:&quot; 的本地化字符串。
        /// </summary>
        public static string weblogindescpre {
            get {
                return ResourceManager.GetString("weblogindescpre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot; 的本地化字符串。
        /// </summary>
        public static string weblogindescsuff {
            get {
                return ResourceManager.GetString("weblogindescsuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 data:image/png;base64, 的本地化字符串。
        /// </summary>
        public static string webloginimgpre {
            get {
                return ResourceManager.GetString("webloginimgpre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot; 的本地化字符串。
        /// </summary>
        public static string webloginimgsuff {
            get {
                return ResourceManager.GetString("webloginimgsuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;selectTitle&quot;:&quot; 的本地化字符串。
        /// </summary>
        public static string webloginselectpre {
            get {
                return ResourceManager.GetString("webloginselectpre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot; 的本地化字符串。
        /// </summary>
        public static string webloginselectsuff {
            get {
                return ResourceManager.GetString("webloginselectsuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;sessionData&quot;:&quot; 的本地化字符串。
        /// </summary>
        public static string webloginsesspre {
            get {
                return ResourceManager.GetString("webloginsesspre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot; 的本地化字符串。
        /// </summary>
        public static string webloginsesssuff {
            get {
                return ResourceManager.GetString("webloginsesssuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;returnCode&quot;:0 的本地化字符串。
        /// </summary>
        public static string webloginsuccess {
            get {
                return ResourceManager.GetString("webloginsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;uid&quot;: 的本地化字符串。
        /// </summary>
        public static string webloginuidpre {
            get {
                return ResourceManager.GetString("webloginuidpre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 , 的本地化字符串。
        /// </summary>
        public static string webloginuidsuff {
            get {
                return ResourceManager.GetString("webloginuidsuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;uri&quot;:&quot;40022&quot;,&quot;version&quot;:&quot;2.2&quot;,&quot;context&quot;:&quot;WB-{SMALL}-{BIG}-&quot;,&quot;appId&quot;:&quot;5002&quot;,&quot;lcid&quot;:&quot;2052&quot;,&quot;byPass&quot;:&quot;3&quot;,&quot;sdid&quot;:&quot;73737534&quot;,&quot;requestId&quot;:&quot;75190725&quot;,&quot;data&quot;:{&quot;uid&quot;:&quot;{UID}&quot;,&quot;sessionData&quot;:&quot;{SESSIONDATA}&quot;}} 的本地化字符串。
        /// </summary>
        public static string webloginverify {
            get {
                return ResourceManager.GetString("webloginverify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36 OPR/26.0.1656.60
        ///Opera/8.0 (Windows NT 5.1; U; en)
        ///Mozilla/5.0 (Windows NT 5.1; U; en; rv:1.8.1) Gecko/20061208 Firefox/2.0.0 Opera 9.50
        ///Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; en) Opera 9.50
        ///Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0
        ///Mozilla/5.0 (X11; U; Linux x86_64; zh-CN; rv:1.9.2.10) Gecko/20100922 Ubuntu/10.10 (maverick) Firefox/3.6.10
        ///Mozilla/5.0  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string webUserAgent {
            get {
                return ResourceManager.GetString("webUserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {&quot;appId&quot;:&quot;5133&quot;,&quot;uri&quot;:30001,&quot;lcid&quot;:2052,&quot;version&quot;:&quot;1.0&quot;,&quot;context&quot;:&quot;1&quot;,&quot;data&quot;:{&quot;userName&quot;:&quot;{myuser}&quot;,&quot;password&quot;:&quot;{mypassword}&quot;,&quot;bizAppids&quot;:[&quot;5133&quot;],&quot;deviceInfo&quot;:{&quot;terminalType&quot;:2,&quot;deviceId&quot;:&quot;{myguid}&quot;},&quot;protoInfo&quot;:{&quot;appSign&quot;:&quot;329027834cda5ea5af099693cf4904e2&quot;,&quot;appVer&quot;:&quot;1.0&quot;}}} 的本地化字符串。
        /// </summary>
        public static string WXAPP_Login {
            get {
                return ResourceManager.GetString("WXAPP_Login", resourceCulture);
            }
        }
    }
}
